src/Entity/Snippet.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use JsonSerializable;

#[ORM\Entity]
class Snippet implements JsonSerializable
{
    #[ORM\Id, ORM\Column(type: 'integer'), ORM\GeneratedValue(strategy: 'SEQUENCE')]
    private int $id;

    public function __construct(
        #[ORM\Column(type: 'text')]
        private readonly string $code,
        #[ORM\Column(unique: true)]
        private readonly string $hash,
        #[ORM\Column(type: 'integer')]
        private readonly int $cyclomaticComplexity,
        #[ORM\Column(type: 'integer')]
        private readonly int $cognitiveComplexity,
    ) {
    }

    public function getHash(): string
    {
        return $this->hash;
    }

    public function getCode(): string
    {
        return $this->code;
    }

    public function getComplexityLevel(): string
    {
        return $this->determineComplexityLevel(
            ($this->getCyclomaticComplexity() + $this->getCognitiveComplexity()) / 2
        );
    }

    public function getCyclomaticComplexity(): int
    {
        return $this->cyclomaticComplexity;
    }

    public function getCyclomaticComplexityLevel(): string
    {
        return $this->determineComplexityLevel($this->getCyclomaticComplexity());
    }

    public function getCognitiveComplexity(): int
    {
        return $this->cognitiveComplexity;
    }

    public function getCognitiveComplexityLevel(): string
    {
        return $this->determineComplexityLevel($this->getCognitiveComplexity());
    }

    /**
     * @return array{
     *     cyclomatic_complexity: array{value: integer, level: string},
     *     cognitive_complexity: array{value: integer, level: string},
     *     complexity_level: string
     * }
     */
    public function jsonSerialize(): array
    {
        return [
            'cyclomatic_complexity' => [
                'value' => $this->getCyclomaticComplexity(),
                'level' => $this->getCyclomaticComplexityLevel(),
            ],
            'cognitive_complexity' => [
                'value' => $this->getCognitiveComplexity(),
                'level' => $this->getCognitiveComplexityLevel(),
            ],
            'complexity_level' => $this->getComplexityLevel(),
        ];
    }

    private function determineComplexityLevel(float $value): string
    {
        return match (true) {
            $value < 4 => 'low',
            $value < 7 => 'moderate',
            $value < 10 => 'high',
            $value < 100 => 'very-high',
            default => 'overkill',
        };
    }
}

templates/_editor.html.twig
{% set default_complexity = 'X' %}
{% set default_level = 'none' %}
{% set default_code = '<?php\n\n// paste your code snippet to calculate complexity\n' %}

<div id="{{ identifier }}" data-complexity-level="{{ snippet.complexityLevel|default(default_level) }}"
     class="editor-wrapper complexity-level-{{ snippet.complexityLevel|default(default_level) }}">
    <i title="Copy Editor Content" class="js-copy-editor copy-editor fa fa-copy"></i>
    <h2>Editor #{{ number }}</h2>
    <textarea class="editor">{{ snippet.code|default(default_code) }}</textarea>
    <div class="code-comment">Press the <i class="fa-solid fa-sync-alt"></i> button to calculate complexities!</div>
    <div class="code-error">
        <i class="fa-solid fa-exclamation-triangle"></i>
        <span>Looks like your code has a syntax error!</span>
    </div>
    <div class="metrics">
        <div class="complexity-badge">
            <div class="js-cyclomatic-complexity metric complexity-level-{{ snippet.cyclomaticComplexityLevel|default(default_level) }}"
                 data-complexity-level="{{ snippet.cyclomaticComplexityLevel|default(default_level) }}">
                <span>{{ snippet.cyclomaticComplexity|default(default_complexity) }}</span>
            </div>
            <div class="label">
                <span>Cyclomatic</span><br />Complexity
            </div>
        </div>
        <div class="actions">
            <button title="Calculate Complexities" class="js-calculate-complexities">
                <i class="fa-solid fa-sync-alt"></i> Calculate Complexities
            </button>
            <button title="Simplify with OpenAI" class="js-simplify-code">
                <i class="fa-solid fa-arrow-trend-down"></i> Simplify with OpenAI
            </button>
            <div class="loading">
                <i class="fa-solid fa-circle-notch fa-spin"></i> Loading response ...
            </div>
        </div>
        <div class="complexity-badge">
            <div class="js-cognitive-complexity metric complexity-level-{{ snippet.cognitiveComplexityLevel|default(default_level) }}"
                 data-complexity-level="{{ snippet.cognitiveComplexityLevel|default(default_level) }}">
                <span>{{ snippet.cognitiveComplexity|default(default_complexity) }}</span>
            </div>
            <div class="label">
                <span>Cognitive</span><br />Complexity
            </div>
        </div>
    </div>
</div>

templates/index.html.twig
{% extends 'layout.html.twig' %}

{% block navigation %}
    {{ parent() }}
    <a class="editor-reset" href="/"><i class="fa fa-times-circle"></i> Reset Editors</a>
{% endblock %}

{% block content %}
    <div class="editor-container">
        {% if missing_diff %}
            <div class="missing-diff">
                <i class="fa fa-exclamation-triangle"></i>
                The complexity diff you are looking for doesn't exist.
            </div>
        {% endif %}
        <div class="grid lg:grid-cols-2 md:grid-cols-1 gap-4">
            {{ include('_editor.html.twig', {number: 1, identifier: 'js-editor-left', snippet: diff.snippetLeft|default(null)}) }}
            {{ include('_editor.html.twig', {number: 2, identifier: 'js-editor-right', snippet: diff.snippetRight|default(null)}) }}
        </div>
        <div class="container share">
            <div>
                <button class="js-permalink-create permalink-create"
                        title="Click to create permalink">
                    <i class="fa fa-share-nodes"></i>
                    Share Complexity Diff
                </button>
                <input type="text" readonly="readonly" class="js-permalink-input"
                       placeholder="&lArr; Click share button to generate permalink to this complexity diff ..."
                       value="{{ diff ? url('decomplex_permalink', {id: diff.id}) }}" />
                <button class="js-permalink-copy permalink-copy" title="Click to copy permalink"><i class="fa fa-copy"></i></button>
            </div>
            <span>
                Please be aware that your code snippets get stored on server-side while using this feature,
                but it's not used for some crazy AI stuff or anything else than the permalink.
            </span>
        </div>
    </div>
    <div class="notes container">
        <h3>Complexity Levels</h3>
        <div class="complexity-bar">
            <div class="complexity-bar-inner">
                <div>
                    <span>Low</span><br />0 &dash; 4
                </div>
                <div>
                    <span>Moderate</span><br />4 &dash; 7
                </div>
                <div>
                    <span>High</span><br />7 &dash; 10
                </div>
                <div>
                    <span>Very High</span><br />> 10
                </div>
            </div>
        </div>
        <h3 class="pt-6">Cyclomatic Complexity</h3>
        <p class="my-4">
            Cyclomatic complexity is computed using the control flow graph of the program: the nodes of the graph
            correspond to indivisible groups of commands of a program, and a directed edge connects two nodes if
            the second command might be executed immediately after the first command. Cyclomatic complexity may
            also be applied to individual functions, modules, methods or classes within a program.
            <a class="underline" href="https://en.wikipedia.org/wiki/Cyclomatic_complexity" target="_blank">See Wikipedia for more information.</a>
        </p>
        <p>
            To measure or enforce cyclomatic complexity limits in your application see
            <a class="underline" href="https://github.com/sebastianbergmann/phploc" target="_blank">PHPLOC</a> or
            <a class="underline" href="https://phpmd.org/" target="_blank">PHP Mess Detector</a>.
        </p>
        <h3 class="pt-8">Cognitive Complexity</h3>
        <p class="my-4">
            Cognitive Complexity is a measure of how difficult a unit of code is to intuitively understand. Unlike
            Cyclomatic Complexity it was formulated with the primary goal of calculating method scores that more
            accurately reflect methods’ relative understandability, and with secondary goals of addressing modern
            language constructs and producing metrics that are valuable above the method level.
            <a class="underline" href="https://www.sonarsource.com/docs/CognitiveComplexity.pdf" target="_blank">See SonarSource's Whitepaper for more information.</a>
        </p>
        <p>
            To enforce cognitive complexity limits in your application with <a href="https://phpstan.org/" target="_blank">PHPStan</a> see
            <a class="underline" href="https://www.tomasvotruba.com/blog/2018/05/21/is-your-code-readable-by-humans-cognitive-complexity-tells-you/" target="_blank">Tomas Votruba's blog post</a>.
        </p>
    </div>
{% endblock %}

templates/layout.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>deComplex.me - diff and reduce the complexity of your PHP code</title>
        <meta property="og:image" content="{{ asset('screenshot.png') }}" />
        <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('apple-touch-icon.png') }}">
        <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('favicon-32x32.png') }}">
        <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('favicon-16x16.png') }}">
        <link rel="manifest" href="{{ asset('site.webmanifest') }}">
        {{ encore_entry_link_tags('app') }}
    </head>
    <body>
        <header>
            <div class="container">
                {% block navigation %}
                    <div>
                        <a href="{{ path('decomplex_index') }}"><img src="{{ asset('decomplex.png') }}" alt="deComplex.me Logo"></a>
                        <span>diff and reduce the complexity of your PHP code</span>
                    </div>
                {% endblock %}
            </div>
        </header>
        {% block content %}{% endblock %}
        <footer class="container">
            <p>
                Powered by
                <a href="https://github.com/NielsdeBlaauw/php-doc-check/" target="_blank">PHP Doc Check</a>,
                <a href="https://codemirror.net/" target="_blank">CodeMirror</a>,
                <a href="https://symfony.com/" target="_blank">Symfony</a> with <a href="https://twig.symfony.com/" target="_blank">Twig</a>,
                <a href="https://tailwindcss.com/" target="_blank">Tailwind CSS</a>,
                <a href="https://sass-lang.com/" target="_blank">Sass</a>,
                <a href="https://jquery.com/" target="_blank">jQuery</a>,
                <a href="https://fontawesome.com/" target="_blank">Font Awesome</a>,
                <a href="https://webpack.js.org/" target="_blank">Webpack</a> with <a href="https://github.com/symfony/webpack-encore" target="_blank">Encore</a>,
                <a href="https://www.postgresql.org/" target="_blank">PostgreSQL</a> and many more.<br />
                Check out the sources at <a class="underline" href="https://github.com/chr-hertel/decomplex" target="_blank">Github</a>.
            </p>
            Made with ♥ in Berlin by <a class="underline" href="//twitter.com/el_stoffel" target="_blank">@el_stoffel</a>
        </footer>
        {{ encore_entry_script_tags('app') }}
    </body>
</html>